nelmio_api_doc:
    documentation:
        info:
            title: NomadTrip API
            description: This is an awesome app that allows you to plan your trips and save your memories.
            version: 1.0.0
            contact:
                name: NomadTrip Team
                email: gilpb.tech@hotmail.com
        components:
            securitySchemes:
                X-AUTH-TOKEN:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - X-AUTH-TOKEN: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

